# Generated by Django 4.1 on 2022-09-28 18:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('idEmpleados', models.AutoField(primary_key=True, serialize=False)),
                ('NomEmpleado', models.CharField(max_length=80, unique=True, verbose_name='nomEpleado')),
                ('CelEmpleado', models.IntegerField(max_length=20, verbose_name='celEmpleado')),
                ('CCEmpleado', models.IntegerField(max_length=20, verbose_name='ccEmpleado')),
                ('RolEmpleado', models.CharField(max_length=20, verbose_name='rolEmpleado')),
                ('StatusEmpleado', models.CharField(max_length=20, verbose_name='statusEmpleado')),
                ('username', models.CharField(max_length=100, unique=True, verbose_name='Username')),
                ('password', models.CharField(max_length=100, verbose_name='Password')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('idCliente', models.BigAutoField(primary_key=True, serialize=False)),
                ('nameCliente', models.CharField(max_length=80, verbose_name='Nombre del cliente: ')),
                ('celCliente', models.IntegerField(max_length=30, verbose_name='Número de celular del cliente: ')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('idCodigoDeProducto', models.BigAutoField(primary_key=True, serialize=False)),
                ('NomProducto', models.CharField(max_length=100, verbose_name='nombreDeProducto')),
                ('DescProducto', models.CharField(max_length=200, verbose_name='descripcionDeProducto')),
                ('ValorUnitario', models.IntegerField(max_length=100, verbose_name='valorUnitario')),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('idpedido', models.AutoField(primary_key=True, serialize=False)),
                ('Codproduct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pedidos', to='autApp.productos')),
            ],
        ),
        migrations.CreateModel(
            name='Facturacion',
            fields=[
                ('idfactura', models.AutoField(primary_key=True, serialize=False)),
                ('celCliente', models.IntegerField(max_length=50, verbose_name='Número de celular del cliente')),
                ('medioPago', models.CharField(max_length=80, verbose_name='Medio de pago')),
                ('valorTotal', models.IntegerField(max_length=50, verbose_name='Valor total')),
                ('clientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Facturacion', to='autApp.clientes')),
                ('empleados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Facturacion', to=settings.AUTH_USER_MODEL)),
                ('pedidos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Facturacion', to='autApp.pedidos')),
            ],
        ),
        migrations.CreateModel(
            name='CarritoDeCompras',
            fields=[
                ('idCodigoDeVenta', models.BigAutoField(primary_key=True, serialize=False)),
                ('cantidadProductos', models.CharField(max_length=80, verbose_name='cantidadProducto')),
                ('ValorUnitario', models.IntegerField(max_length=100, verbose_name='valorUnitario')),
                ('ValorTotal', models.IntegerField(max_length=100, verbose_name='valorTotal')),
                ('medioDePago', models.IntegerField(max_length=100, verbose_name='medioDePago')),
                ('idClient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Clientes', to='autApp.clientes')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Empleados', to=settings.AUTH_USER_MODEL)),
                ('idPedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Pedidos', to='autApp.pedidos')),
            ],
        ),
    ]
